config/routes.rb
Rails.application.routes.draw do

  get '/mechanics' => 'mechanics#index'
  get '/mechanics/update' => 'mechanics#mechanics_update'

  get '/gas' => 'gas#index'
  get '/gas/coords' => 'gas#get_coords'
  get '/vehicles/selling' => 'vehicles#selling'

  match '/contact', to: 'welcomes#home', via: 'get'
  post '/contact', to: 'welcomes#contact'
  post '/transfer_vehicle', to: 'vehicles#transfer'

  devise_for :users
  root "welcomes#home"
  resources :charges
  resources :vehicles do
    resources :repairs
    resources :insurances
    resources :registrations
    resources :oilchanges, controller: 'repairs', type: 'Oilchange'
    resources :tirerotations, controller: 'repairs', type: 'Tirerotation'
    resources :inspections, controller: 'repairs', type: 'Inspection'
    resources :alignments, controller: 'repairs', type: 'Alignment'
    resources :modifications, controller: 'repairs', type: 'Modification'
    resources :otherrepairs, controller: 'repairs', type: 'Otherrepair'
  end

  resources :cars, controller: 'vehicles', type: 'Car'
  resources :trucks, controller: 'vehicles', type: 'Truck'
  resources :boats, controller: 'vehicles', type: 'Boat'
  resources :trailers, controller: 'vehicles', type: 'Trailer'
  resources :atvs, controller: 'vehicles', type: 'Atv'
  resources :motorcycles, controller: 'vehicles', type: 'Motorcycle'
  resources :waverunners, controller: 'vehicles', type: 'Waverunner'
  resources :dunebuggies, controller: 'vehicles', type: 'Dunebuggy'
  resources :other, controller: 'vehicles', type: 'Other'
end

app/models/insurance.rb
class Insurance < ActiveRecord::Base
  belongs_to :vehicle

  has_attached_file :image, styles: { large: "500x500>", medium: "150x150>", thumb: "50x50>"}
  #validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates_attachment_content_type :image, :content_type => /^image\/(jpg|jpeg|pjpeg|png|x-png|gif)$/, :message => 'file type is not allowed (only jpeg/png/gif images)'
end

app/controllers/insurance_controller.rb
class InsuranceController < ApplicationController
  before_action :find_insurance, only: [:edit, :update, :show]
  before_action :find_vehicle
  before_action :authenticate_user!

  def index
    @insurances = Insurance.where(@vehicles.user_id == current_user.id)
  end

  def new
    @insurance = @vehicle.insurances.build
  end

  def create
    @insurance = @vehicle.insurances.build(insurance_params)
    if @insurance.save
      redirect_to(vehicle_insurance_path(@vehicle.id, @insurance.id))
      flash[:notice] = "Insurance was added successfully!"
    else
      flash[:error] = "Insurance was not added."
      render :new
    end
  end

  def edit
  end

  def update
    if @insurance.update(insurance_params)
      flash[:notice] = "Insurance was successfully updated."
      redirect_to(vehicle_insurance_path(@vehicle.id, @insurance.id))
    else
      flash[:error] = "Insurance was not successfully updated."
      render :edit
    end
  end

  def show
  end

  private

  def insurance_params
    params.require(:insurance).permit(:policy_number, :company, :expiration_date, :cost, :image)
  end

  def find_insurance
    @insurance = Insurance.find_by(id: params[:id])
    unless @insurance
      render(text: "Insurance not found.", status: :not_found)
    end
  end

  def find_vehicle
    @vehicle = Vehicle.find_by(id: params[:vehicle_id])
  end

end

app/controllers/insurances_controller.rb
class InsurancesController < ApplicationController
  before_action :find_insurance, only: [:edit, :update, :show]
  before_action :find_vehicle
  before_action :authenticate_user!
  before_action :authenticate_user, only: [:destroy, :edit, :update, :show]

  def index
    if current_user.premium?
      @vehicles = current_user.vehicles.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 9)
    else
      @vehicles = current_user.vehicles.all.take(3)
    end
    #@insurance = Insurance.where(@insurance.vehicle.user_id == current_user.id)
  end

  def new
    @insurance = Insurance.new
  end

  def create
    @insurance = Insurance.new(insurance_params)
    if @insurance.save
      redirect_to(vehicle_insurance_path(@insurance.vehicle_id, @insurance.id))
      flash[:notice] = "Insurance was added successfully!"
    else
      flash[:error] = "Insurance was not added."
      render :new
    end
  end

  def edit
  end

  def update
    if @insurance.update(insurance_params)
      flash[:notice] = "Insurance was successfully updated."
      redirect_to(vehicle_insurance_path(@vehicle.id, @insurance.id))
    else
      flash[:error] = "Insurance was not successfully updated."
      render :edit
    end
  end

  def show
    if params[:layout] == 'false'
      render('show', layout: false)
    end
  end

  private
  def insurance_params
    params.require(:insurance).permit(:policy_number, :company, :expiration_date, :cost, :image, :vehicle_id, :renewal_date)
  end

  def find_insurance
    @insurance = Insurance.find_by(id: params[:id])
    unless @insurance
      render(text: "Insurance not found.", status: :not_found)
    end
  end

  def find_vehicle
    @vehicle = Vehicle.find_by(id: params[:vehicle_id])
  end

  def authenticate_user
    if @vehicle.user_id != current_user.id || @vehicle.insurance.id != params[:id].to_i
      redirect_to vehicles_path
    end
  end

end

app/helpers/insurance_helper.rb
module InsuranceHelper
end

app/views/insurances/edit.html.erb
<div class="container">
  <h1 class="text-center">Edit Insurance for <%= @vehicle.name.capitalize %></h1>
  <hr>
  <div style="text-align:center;">
    <%= form_for @insurance, url: vehicle_insurance_path, :html => { :multipart => true }  do |f| %>
      <% if @insurance.image.present? %>
        <%= image_tag(@insurance.image.url(:medium)) %>
      <% else %>
        <p>Please upload a photo</p>
      <% end %>

      <h2>Company:<br>
        <%= f.text_field :company, class: "form-control", :placeholder => "Company", :style => "width:50%; display:inline-block;" %></h2>
      <br>
      <h3>Policy Number:<br>
        <%= f.text_field :policy_number, class: "form-control", :placeholder => "Policy Number", :style => "width:40%;  display:inline-block;" %></h3>
      <br>
      <h4>Expiration Date:<br>
        <%= f.date_select :expiration_date, class: "form-control", :placeholder => "Expiration Date", :style => "width:60%; display:inline-block;" %></h4>
      <br>
      <h4>Renewal Date:<br>
        <%= f.date_select :renewal_date, class: "form-control", :placeholder => "Renewal Date", :style => "width:60%; display:inline-block;" %></h4>
      <br>
      <h4>Cost:
        <%= f.text_field :cost, class: "form-control", :placeholder => "Cost of Policy (Monthly)", :style => "width:30%; display:inline-block;" %></h4>
      <br>
      <%= f.file_field :image, style: "display:inline-block;" %>
      <br><br>
      <p><%= f.submit :class => "myButton", :style => "margin-right:13%;" %>
        <%= link_to 'Cancel', vehicles_path, :class => "myButton", :method => :get %></p>
      <br><br>

    <% end %>
  </div>
</div>

app/views/insurances/index.html.erb
<div class="text-center container">
  <h1>All Vehicle Insurances</h1><hr>
    <%= link_to 'Back to My Vehicles', vehicles_path, :class => "myButton", :method => :get %>
  <hr />
  <% if @vehicle.insurance.present? %>
    <table class="table table-hover table-striped container">
      <thead>
        <tr>
          <th class="text-center">Vehicle</th>
          <th class="text-center">Company</th>
          <th class="text-center">Policy Number</th>
          <th class="text-center">Expiration Date</th>
          <th class="text-center">Renewal Date</th>
          <th class="text-center">Cost (Monthly)</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @vehicles.each do |i| %>
          <tr>
            <% if i.insurance.present? %>
              <td><%= link_to(i.name, vehicle_path(i.id)) %></td>
              <td><%= link_to(i.insurance.company, vehicle_insurance_path(i.id, i.insurance.id)) %></td>
              <td><%= i.insurance.policy_number %></td>
              <% if i.insurance.expiration_date.present? %>
                <td><%= i.insurance.expiration_date.strftime('%b %d, %Y') %></td>
              <% else %>
                <td>No expiration date entered</td>
              <% end %>
              <% if i.insurance.renewal_date.present? %>
                <td><%= i.insurance.renewal_date.strftime('%b %d, %Y') %></td>
              <% else %>
                <td>No renewel date entered.</td>
              <% end %>
              <% if i.insurance.cost.present? %>
                <td>$ <%= sprintf('%.2f', i.insurance.cost) %></td>
              <% else %>
                <td>$ 0.00</td>
              <% end %>
              <td><a href="<%= edit_vehicle_insurance_path(i.id, i.insurance.id) %>" class="btn btn-info"><span class = "glyphicon glyphicon-pencil"></span></a>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <h3>Please add insurance information for your vehicle.</h3>
  <% end %>
</div>

app/views/insurances/new.html.erb
<div class="container">
  <h1 class="text-center">New Insurance for <%= @vehicle.name.capitalize %></h1>
  <hr>
  <div style="text-align:center;">

    <%= form_for @insurance, url: vehicle_insurances_path(:vehicle_id), :html => { :multipart => true }  do |f| %>

      <h2>Company:<br>
        <%= f.text_field :company, class: "form-control form-align", :placeholder => "Company", :style => "width:400px;" %></h2>
      <br>
      <h3>Policy Number:<br>
        <%= f.text_field :policy_number, class: "form-control form-align", :placeholder => "Policy Number", :style => "width:250px;" %></h3>
      <br>
      <h4>Expiration Date:<br>
        <%= f.date_select :expiration_date, class: "form-control", :placeholder => "Expiration Date", :style => "width:60%;" %></h4>
      <br>
      <h4>Renewal Date:<br>
        <%= f.date_select :renewal_date, class: "form-control", :placeholder => "Renewal Date", :style => "width:60%;" %></h4>
      <br>
      <h4>Monthly Cost ($):<br>
        <%= f.text_field :cost, class: "form-control form-align", :placeholder => "Cost of Policy", :style => "width:150px" %></h4>
      <br>
      <%= f.file_field :image, class: "form-align" %>
      <%= f.hidden_field :vehicle_id, value: @vehicle.id %>
      <br><br>
      <p><%= f.submit "Update Insurance", :class => "myButton registration_button" %> <%= link_to 'Cancel', vehicle_path(@vehicle.id), :class => "myButton", :method => :get %></p>
      <br><br>

    <% end %>
  </div>
</div>

app/views/insurances/show.html.erb
<div class="container">
  <h1 class="text-center">Insurance for <%= @vehicle.name.capitalize %></h1>
  <hr>
  <div class="row">
    <div class="col-md-7 text-center">
      <% if @insurance.image.present? %>
        <%= image_tag(@vehicle.insurance.image.url(:large), style: "max-width:100%;") %>
      <% else %>
        <img class="img-responsive" src="http://placehold.it/700x300" alt="">
      <% end %>
      <br/>
    </div>
    <div class="col-md-5 text-center">
      <h1><%= @insurance.company %> </h1>
      <h2><%= @insurance.policy_number %></h2>
      <h3>Expiration Date: <%= @insurance.expiration_date.strftime('%b %d, %Y') %></h3>
      <h3>Renewal Date: <%= @insurance.renewal_date.strftime('%b %d, %Y') %></h3>
      <% if @insurance.cost.present? %>
        <h3>Monthly Cost: $ <%= sprintf('%.2f', @insurance.cost) %> </h3>
      <% end %>
      <br>
      <p><%= link_to 'Edit', edit_vehicle_insurance_path(@insurance.vehicle_id, @insurance.id), :class => "myButton", :style => "margin-right:13%;" %> <%= link_to 'See this Vehicle', vehicle_path(@vehicle.id), :class => "myButton", :method => :get %></p>
    </div>
  </div>
</div>
<br>