config/routes.rb
Rails.application.routes.draw do

  get '/mechanics' => 'mechanics#index'
  get '/mechanics/update' => 'mechanics#mechanics_update'

  get '/gas' => 'gas#index'
  get '/gas/coords' => 'gas#get_coords'
  get '/vehicles/selling' => 'vehicles#selling'

  match '/contact', to: 'welcomes#home', via: 'get'
  post '/contact', to: 'welcomes#contact'
  post '/transfer_vehicle', to: 'vehicles#transfer'

  devise_for :users
  root "welcomes#home"
  resources :charges
  resources :vehicles do
    resources :repairs
    resources :insurances
    resources :registrations
    resources :oilchanges, controller: 'repairs', type: 'Oilchange'
    resources :tirerotations, controller: 'repairs', type: 'Tirerotation'
    resources :inspections, controller: 'repairs', type: 'Inspection'
    resources :alignments, controller: 'repairs', type: 'Alignment'
    resources :modifications, controller: 'repairs', type: 'Modification'
    resources :otherrepairs, controller: 'repairs', type: 'Otherrepair'
  end

  resources :cars, controller: 'vehicles', type: 'Car'
  resources :trucks, controller: 'vehicles', type: 'Truck'
  resources :boats, controller: 'vehicles', type: 'Boat'
  resources :trailers, controller: 'vehicles', type: 'Trailer'
  resources :atvs, controller: 'vehicles', type: 'Atv'
  resources :motorcycles, controller: 'vehicles', type: 'Motorcycle'
  resources :waverunners, controller: 'vehicles', type: 'Waverunner'
  resources :dunebuggies, controller: 'vehicles', type: 'Dunebuggy'
  resources :other, controller: 'vehicles', type: 'Other'
end

app/models/alignment.rb
class Alignment < Repair
  def type_string
    "Alignment"
  end
end

app/models/atv.rb
class ATV < Vehicle

end

app/models/boat.rb
class Boat < Vehicle

end

app/models/car.rb
class Car < Vehicle
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :first_name, :validate => true
  attribute :last_name, :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :phone
  attribute :message

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "New GloveBox Message from #{first_name} #{last_name}",
      :to => "gloveboxteam@gmail.com",
      :from => %("#{first_name} #{last_name}" <#{email}>)
    }
  end
end

app/models/dunebuggy.rb
class Dunebuggy < Vehicle

end

app/models/gas.rb
class Gas < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode
end

app/models/inspection.rb
class Inspection < Repair
  def type_string
    "Inspection"
  end
end

app/models/insurance.rb
class Insurance < ActiveRecord::Base
  belongs_to :vehicle

  has_attached_file :image, styles: { large: "500x500>", medium: "150x150>", thumb: "50x50>"}
  #validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates_attachment_content_type :image, :content_type => /^image\/(jpg|jpeg|pjpeg|png|x-png|gif)$/, :message => 'file type is not allowed (only jpeg/png/gif images)'
end

app/models/motorcycle.rb
class Motorcycle < Vehicle

end

app/models/oilchange.rb
class Oilchange < Repair
  def type_string
    "Oil Change"
  end
end

app/models/other.rb
class Other < Vehicle

end

app/models/otherrepair.rb
class Otherrepair < Repair
  def type_string
    "Other Repair"
  end
end

app/models/repair.rb
class Repair < ActiveRecord::Base
  belongs_to :vehicle
  validates_presence_of :type
  has_attached_file :repair_image, :styles => {:large => "600x600", :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  #validates_attachment_content_type :repair_image, :content_type => /\Aimage\/.*\Z/
  validates_attachment_content_type :repair_image, :content_type => /^image\/(jpg|jpeg|pjpeg|png|x-png|gif)$/
  def self.types
    %w[Oilchange Tirerotation Inspection Alignment Modification Otherrepair]
  end

  #scopes
	def self.oilchanges
		where(type: 'Oilchange')
	end
  def self.tirerotations
		where(type: 'Tirerotation')
	end
  def self.inspections
    where(type: 'Inspection')
  end
  def self.alignments
    where(type: 'Alignment')
  end
  def self.modifications
    where(type: 'Modification')
  end
  def self.otherrepairs
    where(type: 'Otherrepair')
  end

  # def type_string
  #   raise "override me in the subclass"
  # end

end

app/models/trailer.rb
class Trailer < Vehicle

end

app/models/truck.rb
class Truck < Vehicle

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :vehicles, dependent: :destroy
  enum membership: [:basic, :premium]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  has_one :insurance, dependent: :destroy
  has_one :registration, dependent: :destroy
  belongs_to :user
	has_many :repairs, dependent: :destroy

	self.inheritance_column = :type

  has_attached_file :image,
                    styles: { large: "500x500>", medium: "150x150>", thumb: "50x50>"}

  #validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates_attachment_content_type :image, :content_type => /^image\/(jpg|jpeg|pjpeg|png|x-png|gif)$/
  validates :make, :model, :name, :state, :presence => {:message => "empty value found"}

	def self.type
	  %w(Car Truck Boat Trailer ATV Motorcycle Waverunner Dunebuggy Other)
	end

	#scopes
	def self.car
		where(type: 'Car')
	end

	def self.truck
		where(type: 'Truck')
	end

	def self.boat
		where(type: 'Boat')
	end

	def self.trailer
		where(type: 'Trailer')
	end

  def self.atv
    where(type: 'ATV')
  end

  def self.motorcycle
    where(type: 'Motorcycle')
  end

  def self.waverunner
    where(type: 'Waverunner')
  end

  def self.dunebuggy
    where(type: 'Dunebuggy')
  end

  def self.other
    where(type: 'Other')
  end

	# def talk
	#   raise 'You need to override this method in your sub classes'
	# end

end

app/models/waverunner.rb
class Waverunner < Vehicle

end

app/controllers/welcome_controller.rb
class WelcomesController < ApplicationController
  def home
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def home
    @contact = Contact.new
  end

  def contact
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash[:notice] = 'Thank you for your message. We appreciate the feedback!'
      redirect_to root_path
    else
      flash[:error] = 'Cannot send message.'
      redirect_to root_path
    end
  end
end

app/helpers/gas_helper.rb
module GasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcomes/home.html.erb
<div class="road_header text-center">
  <h1>GLOVEBOX</h1>
  <h3>all your vehicle information at your fingertips</h3>
  <% if user_signed_in? %>
  <% else %>
    <%= link_to 'LOGIN', new_user_session_path, :class => "btn btn-default", :style => "margin-right: 5%; margin-bottom:5%;padding-left:1%;padding-right:1%;" %>
    <%= link_to 'SIGN UP', new_user_registration_path, :class => "btn btn-default", :style => "margin-bottom:5%;padding-left:1%;padding-right:1%;" %>
  <% end %>
</div>
<hr>
<div class="text-center container">
  <div class="features">
    <h2 style="font-size:25px;">Features of GloveBox</h2>
    <br>
    <span class="col-sm-4 col-xs-12">
      <%= link_to image_tag("caricon.png", width: "135px", alt: "car"), vehicles_path %><h4 style="font-size:15px;">Store Vehicle Information</h4>
    </span>
    <span class="col-sm-4 col-xs-12">
      <%= link_to image_tag("papersicon.png", width: "135px", alt: "files"), vehicles_path %><h4 style="font-size:15px;">File Maintenance Records</h4>
    </span>
    <span class="col-sm-4 col-xs-12">
      <% if current_user && current_user.basic? %>
        <%= link_to image_tag("remindericon.png", width: "135px", alt: "reminder"), new_charge_path %><h4 style="font-size:15px;">Receive Reminders for Maintenance <br><strong>Premium Members Only</strong></h4>
      <% else %>
        <%= link_to image_tag("remindericon.png", width: "135px", alt: "reminder"), edit_user_registration_path %><h4 style="font-size:15px;">Receive Reminders for Maintenance <br><strong>Premium Members Only</strong></h4>
      <% end %>
    </span>
  </div>
</div>
<br><hr>
<div class="details text-center">
  <hr>
  <table>
    <thead>
      <hr>
      <h2 style="font-size:25px;">What we can do for you...</h2>
      <br>
    </thead>
    <tr>
      <td class="arrow"><%= image_tag("arrowicon.png", width: "15%", alt: "arrow") %></td>
      <td class="sentence"><h4>Have quick access to details about each of your vehicles.</h4></td>
    </tr>
    <tr>
      <td class="arrow"><%= image_tag("arrowicon.png", width: "15%", alt: "arrow") %></td>
      <td class="sentence"><h4>Maintain all records pertaining to your vehicle: insurance, registration, maintenance, etc.</h4></td>
    </tr>
    <tr>
      <td class="arrow"><%= image_tag("arrowicon.png", width: "15%", alt: "arrow") %></td>
      <td class="sentence"><h4>Receive reminders for oil changes, tire rotations, insurance renewal, registration renewal, etc.<strong>  &nbsp;-  Premium Members Only</strong></h4></td>
    </tr>
    <tr>
      <td class="arrow"><%= image_tag("arrowicon.png", width: "15%", alt: "arrow") %></td>
      <td class="sentence"><h4>Transfer entire vehicle file to new owners.</h4></td>
    </tr>
    <tr>
      <td class="arrow"><%= image_tag("arrowicon.png", width: "15%", alt: "arrow") %></td>
      <td class="sentence"><h4>Get information about selling your vehicle.</h4></td>
    </tr>
    <tr>
      <td class="arrow"><%= image_tag("arrowicon.png", width: "15%", alt: "arrow") %></td>
      <td class="sentence"><h4>Find a mechanic in your area and see their user rating.</h4></td>
    </tr>
  </table>
  <hr><br>
</div>
<hr>
<div class="extra_features text-center container">
  <div class="extra">
    <h2 style="font-size:28px;">Other Features of GloveBox</h2>
    <br>
    <span class="col-sm-4 col-xs-12"><%= link_to image_tag("gasicon.png", width: "120px", alt: "gas"), gas_path %><h4 style="font-size:13px;">Find the Best Gas Prices</h4></span>
    <span class="col-sm-4 col-xs-12"><%= link_to image_tag("mechanicicon.png", width: "135px", alt: "mechanic"), vehicles_selling_path %><h4 style="font-size:13px;">Transfer Your Repair Files When You Sell</h4></span>
    <span class="col-sm-4 col-xs-12"><%= link_to image_tag("partsicon.png", width: "120px", alt: "parts"), mechanics_path %><h4 style="font-size:13px;">Search Local Mechanics</h4></span>
  </div>
</div>
<hr>
<div id="membership" style="background-color:black; color:black"><br><hr>
  <h2 class="text-center" style="color:white;">Basic Versus Premium Membership:</h2>
  <br>
  <div class="container">
    <div class="col-md-6 col-sm-12 gray-box" style="height:300px; background-color:#ADADAD;"><br>
      <div style="height: 240px; border:3px solid black; margin:2%">
        <div class="container" style="margin:2%">
          <h5>Basic</h5>
          <h1>FREE</h1>
          <ul>
            <li>Save up to three vehicles</li>
            <li>Store vehicle details like insurance and registration</li>
            <li>Maintain and file vehicle repairs</li>
            <li>Track vehicle repair costs</li>
          </ul>
          <br>
        </div>
      </div>
    </div>

    <div class="col-md-6 col-sm-12 red-box" style="height:300px; background-color:#D91F0F;"><br>
      <div style="height: 240px; border:3px solid black; margin: 2%;">
        <div class="container" style="margin:2%;max-width:100%">
          <h5>Premium</h5>
          <h6 style="margin-bottom:0%;margin-top:3.1%">ONLY</h6>
          <h2 style="margin-top:0%;">$5 / year </h2>
          <h4 style="margin-top:2%;">All the benefits of basic, plus:</h4>
          <ul>
            <li>Save an UNLIMITED number of vehicles</li>
            <li>Receive reminders for updating insurance and registration</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <% if user_signed_in? == false %>
    <div class="text-center">
      <p><%= link_to 'Sign Up', new_user_registration_path, class: "myButton", style: "margin-left: auto; margin-right:auto; font-size: 20px;" %></p>
    </div>
  <% end %>
  <hr><br>
</div>
<div id="about-us" class="text-center" style="background-color:#F7F7F6;padding-bottom:4%;">
  <div class="about-us container">
    <br>
    <h2 style="font-size:28px;">The GLOVEBOX Team</h2><br>
    <h4>The GLOVEBOX Team was assembled as a Final Project upon graduating from a rails bootcamp experience at <a href="http://www.devpointlabs.com/">DevPoint Labs</a>.
    </h4><br><br>
    <span id="brad" style="padding-bottom:4%;" class="bio col-sm-3 col-xs-12" data-toggle="popover" data-placement="bottom" title="Brad Hintze" data-content="Born in California and raised in Utah, Brad is a 29 year old Air Force Veteran with a bachelors degree in Computer Information Systems.   Brad has enjoyed programming ever since his first college programming course where he learned C#.  He wanted to learn more and signed up for DevPoint Labs."><%= image_tag("bradley.jpg", width: "135px", alt: "Brad") %><h4 style="font-size:15px;margin-bottom:0%;">Brad Hintze | <%= link_to "Bio", 'http://brad-hintze.herokuapp.com/', :target => "_blank" %></h4></span>

    <span id="carter" style="padding-bottom:4%;" class="bio col-sm-3 col-xs-12" data-toggle="popover" data-placement="bottom" title="Carter Graves" data-content="Carter has lived in Utah for the majority of his life, he spent 6 years in Tennessee and is 28 years old. Carter enjoys auto racing. After working along side software developers for a few years at a previous job he is looking to enter the world of software development for himself."><%= image_tag("Carter.jpg", width: "135px", alt: "Carter") %><h4 style="font-size:15px;margin-bottom:0%;">Carter Graves | <%= link_to "Bio", 'http://cartersbio.herokuapp.com/', :target => "_blank" %></h4></span>

     <span id="meg" style="padding-bottom:4%;" class="bio col-sm-3 col-xs-12" data-toggle="popover" data-placement="bottom" title="Meg Svetz" data-content="Meg began doing photography nine years ago, which slowly transformed into a love of design. Wanting to get more control over design and be able to create from the ground up, she decided to enroll at DevPoint Labs. She never imagined just how much she would enjoy programming."><%= image_tag("meg.jpg", width: "135px", alt: "Meg") %><h4 style="font-size:15px;margin-bottom:0%;">Meg Svetz | <%= link_to "Bio", 'http://www.megsvetz.com/', :target => "_blank" %></h4></span>

    <span id="steve" style="padding-bottom:4%;" class="bio col-sm-3 col-xs-12" data-toggle="popover" data-placement="bottom" title="Stephen Thomas" data-content="Stephen was born and raised in Utah. All throughout high school, he was interested in a career in computers. In 2013, Stephen took his first programming course and has never looked back. Web development and other types of programming are his passion because he can express himself and contribute to society. Stephen is currently studying at Brigham Young University to further his education and receive a bachelors/masters in information systems management."><%= image_tag("Steve.jpg", width: "135px", alt: "Stephen") %><h4 style="font-size:15px;margin-bottom:0%;">Stephen Thomas | <%= link_to "Bio", 'https://github.com/gamgi1', :target => "_blank" %></h4></span>
  </div>
  <br>
</div>
<hr>
<div id="contact-us" class="text-center">
  <br>
  <h2 style="font-size:28px;">Contact Us</h2><br>
    <%= form_for @contact, url: contact_path do |f| %>
    <!-- <form class="" action="/contact" method="POST"> -->
      <div class="row">
        <div class="col-md-3 col-sm-4 col-sm-offset-2 col-md-offset-3">
          <%= f.text_field :first_name, class: "contact-form-fields", :placeholder=>"First Name", :required => true %>
          <!-- <input class="contact-form-fields" type="text" name="first_name" placeholder="First Name"> -->
        </div>
        <div class="col-md-3 col-sm-4">
          <%= f.text_field :last_name, class: "contact-form-fields", :placeholder =>"Last Name", :required => true %>
          <!-- <input class="contact-form-fields" type="text" name="last_name" placeholder="Last Name"> -->
        </div>
      </div>
      <div class="row">
        <div class="col-md-3 col-sm-4 col-sm-offset-2 col-md-offset-3">
          <%= f.text_field :email, class: "contact-form-fields", :placeholder => "Your Email Address", :required => true %>
          <!-- <input class="contact-form-fields" type="text" name="email" placeholder="Your Email Address"> -->
        </div>
        <div class="col-md-3 col-sm-4">
          <%= f.text_field :phone, class: "contact-form-fields", :placeholder => "Your Phone Number" %>
          <!-- <input class="contact-form-fields" type="phone" name="phone" placeholder="Your Phone Number"> -->
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 col-sm-8 col-sm-offset-2 col-md-offset-3">
          <%= f.text_area :message, class: "contact-form-fields", :placeholder => "Have ideas to improve GloveBox? Let us know how!", :required => true%>
          <!-- <textarea class="contact-form-fields form-message" name="body" placeholder="Have ideas to improve Glovebox? Let us know how!" type="text"></textarea> -->
        </div>
      </div>
      <div class="row">
          <div class="col-md-6 col-sm-8 col-sm-offset-2 col-md-offset-3">
            <div class="myButton" id='send_button'>Send</div>
            <div class="myButton" id='clear_form'>Cancel</div>
          </div>
      </div>
    <!-- </form> -->
    <% end %>
  <br>
  <hr>
</div>