config/routes.rb
Rails.application.routes.draw do

  get '/mechanics' => 'mechanics#index'
  get '/mechanics/update' => 'mechanics#mechanics_update'

  get '/gas' => 'gas#index'
  get '/gas/coords' => 'gas#get_coords'
  get '/vehicles/selling' => 'vehicles#selling'

  match '/contact', to: 'welcomes#home', via: 'get'
  post '/contact', to: 'welcomes#contact'
  post '/transfer_vehicle', to: 'vehicles#transfer'

  devise_for :users
  root "welcomes#home"
  resources :charges
  resources :vehicles do
    resources :repairs
    resources :insurances
    resources :registrations
    resources :oilchanges, controller: 'repairs', type: 'Oilchange'
    resources :tirerotations, controller: 'repairs', type: 'Tirerotation'
    resources :inspections, controller: 'repairs', type: 'Inspection'
    resources :alignments, controller: 'repairs', type: 'Alignment'
    resources :modifications, controller: 'repairs', type: 'Modification'
    resources :otherrepairs, controller: 'repairs', type: 'Otherrepair'
  end

  resources :cars, controller: 'vehicles', type: 'Car'
  resources :trucks, controller: 'vehicles', type: 'Truck'
  resources :boats, controller: 'vehicles', type: 'Boat'
  resources :trailers, controller: 'vehicles', type: 'Trailer'
  resources :atvs, controller: 'vehicles', type: 'Atv'
  resources :motorcycles, controller: 'vehicles', type: 'Motorcycle'
  resources :waverunners, controller: 'vehicles', type: 'Waverunner'
  resources :dunebuggies, controller: 'vehicles', type: 'Dunebuggy'
  resources :other, controller: 'vehicles', type: 'Other'
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  has_one :insurance, dependent: :destroy
  has_one :registration, dependent: :destroy
  belongs_to :user
	has_many :repairs, dependent: :destroy

	self.inheritance_column = :type

  has_attached_file :image,
                    styles: { large: "500x500>", medium: "150x150>", thumb: "50x50>"}

  #validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates_attachment_content_type :image, :content_type => /^image\/(jpg|jpeg|pjpeg|png|x-png|gif)$/
  validates :make, :model, :name, :state, :presence => {:message => "empty value found"}

	def self.type
	  %w(Car Truck Boat Trailer ATV Motorcycle Waverunner Dunebuggy Other)
	end

	#scopes
	def self.car
		where(type: 'Car')
	end

	def self.truck
		where(type: 'Truck')
	end

	def self.boat
		where(type: 'Boat')
	end

	def self.trailer
		where(type: 'Trailer')
	end

  def self.atv
    where(type: 'ATV')
  end

  def self.motorcycle
    where(type: 'Motorcycle')
  end

  def self.waverunner
    where(type: 'Waverunner')
  end

  def self.dunebuggy
    where(type: 'Dunebuggy')
  end

  def self.other
    where(type: 'Other')
  end

	# def talk
	#   raise 'You need to override this method in your sub classes'
	# end

end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :find_vehicle, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :authenticate_user, only: [:show, :edit, :update, :destory]
  before_action :check_membership, only: [:new, :create]
  before_action :validate_vehicle, only: [:show, :edit]

  def index
    @vehicles = current_user.vehicles.all.order("created_at ASC").paginate(:page => params[:page], :per_page => 9)
  end

  def show
  end

  def edit
  end

  def transfer
    vehicle = Vehicle.find(params[:vehicle])
    sender = User.find_by(id: vehicle.user_id).email
    if vehicle.insurance.present?
      vehicle.insurance.destroy
    end
    if vehicle.registration.present?
      vehicle.registration.destroy
    end
    vehicle.user_id = User.find_by(email: params[:new_owner_email]).id
    if vehicle.user_id
      receiver = User.find_by(email: params[:new_owner_email]).email
      vehicle.save
      Reminders.vehicle_transfer(receiver, sender, vehicle).deliver
    else
      flash[:error] = "Could not find user with email of #{params[:new_owner_email]} on GLOVEBOX %>"
    end
    redirect_to :back
  end

  def new
    @vehicle = Vehicle.new
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    # @vehicle.image = "/assets/default_car.jpg"
    if @vehicle.save
      redirect_to vehicles_path, notice: "#{@vehicle.type} was successfully created."
    else
      render :new, notice: 'Vehicle not created'
    end

	end

  def update
    @vehicle.update(vehicle_params)
    redirect_to vehicle_path(@vehicle.id), notice: "#{@vehicle.type} was successfully updated."
  end

  def destroy
    @vehicle.destroy
    redirect_to vehicles_path
  end

  def selling
    @vehicles = current_user.vehicles.all.order("created_at ASC")
  end

  private
  def find_type
    Vehicle.type.include?(params[:type]) ? params[:type] : "Vehicle"
  end

  def vehicle_params
    params.require(find_type.underscore.to_sym).permit(:type, :make, :model, :year, :mileage, :name, :vin, :license_plate, :state, :user_id, :image)
  end

  def find_vehicle
    @vehicle = Vehicle.find_by(id: params[:id])
  end

  def authenticate_user
    if @vehicle.user_id != current_user.id
      redirect_to vehicles_path
    end
  end

  def check_membership
    if current_user.basic? && current_user.vehicles.count >= 3
      redirect_to new_charge_path, notice: "Members with the basic plan are only allowed 3 cars"
    end
  end

  def validate_vehicle
    @vehicles = current_user.vehicles.all.order("created_at ASC")
    if current_user.basic? && @vehicles.length > 3
      @vehicles = [current_user.vehicles.second, current_user.vehicles.third, current_user.vehicles.first]
    end
    bool = @vehicles.any? {|vehicle| @vehicle == vehicle }
    if bool == false
      redirect_to new_charge_path
    end
  end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper

end

app/views/vehicles/_insurance_modal.html.erb
<div class="modal fade" id="insurance_modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <% if @vehicle && @vehicle.insurance %>
        <div class="modal-header">
          <h4 class="modal-title">Insurance for <%= @vehicle.name.capitalize %></h4>
        </div>
        <div class="modal-body">
          <% if @vehicle.insurance.image.present? %>
            <%= link_to image_tag(@vehicle.insurance.image.url(:large)) %>
          <% else %>
            <img class="img-responsive" src="http://placehold.it/700x300" alt="">
          <% end %>
        </div>
      <% else %>
        <div class="modal-body"></div>  
      <% end %>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/vehicles/_registration_modal.html.erb
<div class="modal fade" id="registration_modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <% if @vehicle && @vehicle.registration %>
        <div class="modal-header">
          <h4 class="modal-title">Registration for <%= @vehicle.name.capitalize %></h4>
        </div>
        <div class="modal-body" >
          <% if @vehicle.registration.image.present? %>
            <%= link_to image_tag(@vehicle.registration.image.url(:large)) %>
          <% else %>
            <img class="img-responsive" src="http://placehold.it/700x300" alt="">
          <% end %>
        </div>
      <% else %>
        <div class="modal-body"></div>
      <% end %>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/vehicles/edit.html.erb
<div class='text-center container'>
  <h1>Edit <%= @vehicle.name.capitalize %></h1>
  <hr>
  <div class="form">
    <%= form_for @vehicle do |f| %>
      <%= f.select :type, Vehicle.type, {:include_blank => "Select Vehicle Type"} %><br><br>
      <% dates = 1900..Date.today.year %>
      <p><%= f.select :year, (Time.zone.now.year - 100)..(Time.zone.now.year + 1), {:include_blank => "Select Vehicle Year"} %></p>
      <p><%= f.text_field :make, class: "form-control", :placeholder => "Vehicle Make" %></p>
      <p><%= f.text_field :model, class: "form-control", :placeholder => "Vehicle Model" %></p>
      <p><%= f.text_field :mileage, class: "form-control", :placeholder => "Vehicle Mileage" %></p>
      <p><%= f.text_field :name, class: "form-control", :placeholder => "Vehicle Name" %></p>
      <p><%= f.text_field :vin, class: "form-control", :placeholder => "Vehicle Vin" %></p>
      <p><%= f.text_field :license_plate, class: "form-control", :placeholder => "Vehicle License Plate" %></p>
      <p><%= f.text_field :state, class: "form-control", :placeholder => "State registered in" %></p>
      <p><%= f.file_field :image %></p><br>
      <p><%= f.submit :class => "myButton" %> <%= link_to 'Cancel', vehicle_path(@vehicle.id), :class => "myButton", :method => :get %></p>
    <% end %>
  </div>
</div>

app/views/vehicles/for_sale.html.erb
<div class='vehicle-header text-center'>Selling your Vehicle</div>

  <hr />
  <% unless @vehicles.blank? %>
    <hr>
    <div class="row">
      <% @vehicles.each do |vehicle| %>
        <div class="col-sm-6 col-md-4">
          <div class="thumbnail vehicle_show" style="margin-left:auto; margin-right:auto;">
            <%= link_to(image_tag(vehicle.image.url(:medium)), vehicle_path(vehicle.id)) %>
            <div class="caption">
              <div class='vehicle-text'><%= link_to vehcile.make + ' ' + vehicle.model, vehicle_path(vehicle.id) %>
                <br>
                Mileage: <%= vehicle.mileage %><br>
              </div>
              <br>
              <p>
              <div class='text-center'><%= link_to 'See Repairs', vehicle_repairs_path(a.id), class: 'btn btn-default'%></div></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <%= will_paginate @vehicles %>
</div>
<% else %>
  <h3 class="text-center">It appears that there are no vehicles for sale.</h3>
<% end %>

app/views/vehicles/index.html.erb
<div class='vehicle-header text-center'>Your Vehicles</div>

  <hr />
  <% unless @vehicles.blank? %>
  <div class="text-center"><p><%= link_to 'See All Vehicle Insurances', vehicle_insurances_path(@vehicles.first.id), class: 'btn btn-default', style: 'font-size:.75em; margin-right:5%;' %>
    <%= link_to 'See All Vehicle Registrations', vehicle_registrations_path(@vehicles.first.id), class: 'btn btn-default', style: 'font-size:.75em' %></p>
  </div>
    <hr>
    <div class="row">
      <% @vehicles.each_with_index do |vehicle, index| %>
        <% if current_user.basic? && index > 2 %>
          <div class="col-sm-6 col-md-4" >
            <div class="thumbnail vehicle_show grayed-out" style="margin-left:auto; margin-right:auto; max-width:100%;">
              <% if vehicle.image.present? %>
                <%= link_to image_tag(vehicle.image.url(:medium), vehicle_path(vehicle.id)), style: "margin-left:auto; margin-right:auto; max-width:100%;" %>
              <% else %>
                <%= link_to image_tag("default_car.jpg", :style => "height:150px; width:auto; margin-left:auto; margin-right:auto; max-width:100%;"), vehicle_path(vehicle.id) %>
              <% end %>
              <div class="caption">
                <div class='vehicle-text'><%= vehicle.make + ' ' + vehicle.model %>
                  <br>
                  <% if vehicle.registration.present? %>
                    Reg Expires: <%= vehicle.registration.expiration.strftime('%b %d, %Y') %>
                  <% else %>
                    No Registration Entered!
                  <% end %>
                  <br>
                  <% if vehicle.insurance.present? %>
                    Insurance Expires: <%= vehicle.insurance.expiration_date.strftime('%b %d, %Y') %>
                  <% else %>
                    No Insurance Entered!
                  <% end %>
                  <br>
                  Mileage: <%= vehicle.mileage %><br>
                </div>
                <br>
                <p><div class='text-center'><a href="#" class="btn btn-default">See Repairs</a></div></p>
                <% if vehicle.insurance.present? %>
                  <p><div class="text-center insurance_modal_button btn myButton" data-vehicle="">Insurance</div>
                <% else %>
                  <p><div class='text-center'><a href="#" class="btn myButton" style="font-size:.75em">Add Insurance</a></div>
                <% end %>
                <% if vehicle.registration.present? %>
                  <p><div class="registration_modal_button btn myButton" data-vehicle="<%= vehicle.to_json(include: :registration) %>">Registration</div></p>
                <% else %>
                  <div><a href="#" class="btn myButton" style="font-size:.75em">Add Registration</a></div>
                <% end %>
                </p>
              </div>
            </div>
          </div>
        <% else %>
          <div class="col-sm-6 col-md-4">
            <div class="thumbnail vehicle_show" style="margin-left:auto; margin-right:auto; max-width:100%;">
              <% if vehicle.image.present? %>
                <%= link_to image_tag(vehicle.image.url(:medium), style: "margin-left:auto; margin-right:auto; max-width:100%;"), vehicle_path(vehicle.id) %>
              <% else %>
                <%= link_to image_tag("default_car.jpg", :style => "height:150px; width:auto; margin-left:auto; margin-right:auto; max-width:100%;"), vehicle_path(vehicle.id) %>
              <% end %>
              <div class="caption">
                <div class='vehicle-text'><%= link_to vehicle.make + ' ' + vehicle.model, vehicle_path(vehicle.id) %>
                  <br>
                  <% if vehicle.registration.present? %>
                    Reg Expires: <%= vehicle.registration.expiration.strftime('%b %d, %Y') %>
                  <% else %>
                    No Registration Entered!
                  <% end %>
                  <br>
                  <% if vehicle.insurance.present? %>
                    Insurance Expires: <%= vehicle.insurance.expiration_date.strftime('%b %d, %Y') %>
                  <% else %>
                    No Insurance Entered!
                  <% end %>
                  <br>
                  Mileage: <%= vehicle.mileage %><br>
                </div>

                <br>
                <p><div class='text-center'><%= link_to 'See Repairs', vehicle_repairs_path(vehicle.id), class: 'btn btn-default'%></div></p>
                <% if vehicle.insurance.present? %>
                  <p><div class='text-center'><div class="insurance_modal_button btn myButton" data-vehicle="<%= vehicle.to_json(include: :insurance) %>">Insurance</div>
                <% else %>
                  <p><div class='text-center'><%= link_to 'Add Insurance', new_vehicle_insurance_path(vehicle.id), class: 'btn myButton', style: 'font-size:.8em; padding-right:3%; padding-left:3%;' %>
                <% end %>
                <% if vehicle.registration.present? %>
                  <div class="registration_modal_button btn myButton" data-vehicle="<%= vehicle.to_json(include: :registration) %>">Registration</div></div>
                <% else %>
                  <%= link_to 'Add Registration', new_vehicle_registration_path(vehicle.id), class: 'btn myButton', style: 'font-size:.8em; padding-right:3%; padding-left:3%;' %></div>
                <% end %>
                </p>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
      <% if current_user.basic? && current_user.vehicles.count <= 2 %>
        <div class='col-sm-6 col-md-4'>
          <div class='thumbnail row vehicle_show'  style="margin-left:auto; margin-right:auto; max-width:100%;">
            <%= link_to '', new_vehicle_path, class: "text-center btn btn-lg glyphicon glyphicon-plus btn-success add-button", style:"padding-left:auto; padding-right:auto;" %>
          </div>
        </div>
      <% elsif current_user.premium? %>
         <div class='col-sm-6 col-md-4'>
          <div class='thumbnail row vehicle_show'  style="margin-left:auto; margin-right:auto; max-width:100%;">
            <%= link_to '', new_vehicle_path, class: "btn btn-success btn-lg glyphicon glyphicon-plus text-center add-button" %>
          </div>
        </div>
      <% end %>
    </div>
    <%= will_paginate @vehicles %>
</div>
<% else %>
  <h3 class="text-center">It appears that you have no vehicles. To experience the best of what GloveBox has to offer click the "New Vehicle" button below.</h3>
  <div class="col-sm-offset-5 col-sm-2">
    <%= link_to 'New Vehicle', new_vehicle_path, class: 'btn btn-form-submit' %>
  </div>
<% end %>

<% unless @vehicle.present? %>
  <% @vehicle = Vehicle.new %>
<% end %>
<%= render(partial: "vehicles/insurance_modal") %>
<%= render(partial: "vehicles/registration_modal") %>

app/views/vehicles/new.html.erb
<div class='text-center container'>
  <h1>Add New Vehicle</h1>
  <hr>
  <div class="form">
    <%= form_for(@vehicle, multipart: true) do |f| %>
      <p class='vin-number'><%= f.text_field :vin, class: "form-control", :placeholder => "Vehicle Vin", :style => "width:100%;" %></p>
      <%= f.select :type, Vehicle.type, {:include_blank => "Select Vehicle Type"}, style:"margin-bottom:8%;", required: :true %>
      <% dates = 1900..Date.today.year %>
      <%= f.select :year, ((Time.zone.now.year - 50)..(Time.zone.now.year + 1)).to_a.reverse, {:include_blank => "Select Vehicle Year"}, required: :true %>
      <br><br>
      <p><%= f.text_field :make, class: "form-control v-make required", :placeholder => "Vehicle Make *", :style => "width:100%;", required: :true %></p>
      <p><%= f.text_field :model, class: "form-control v-model", :placeholder => "Vehicle Model *", :style => "width:100%;", required: :true %></p>
      <p><%= f.text_field :name, class: "form-control", :placeholder => "Vehicle Name *", :style => "width:100%;", required: :true %></p>
      <p><%= f.text_field :mileage, class: "form-control", :placeholder => "Vehicle Mileage", :style => "width:100%;" %></p>
      <p><%= f.text_field :license_plate, class: "form-control", :placeholder => "Vehicle License Plate", :style => "width:100%;" %></p>
      <p><%= f.text_field :state, class: "form-control", :placeholder => "State registered in *", :style => "width:100%;", required: :true %></p>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <p style="color: #bababa;">* required fields</p><br>
      <p><%= f.file_field :image %></p>
      <p style="color:lightgray">(Accepted Image Types: JPG/JPEG/GIF/PNG)</p>
      <p><%= f.submit :class => "myButton" %> <%= link_to 'Cancel', vehicles_path, :class => "myButton", :method => :get %></p>
    <% end %>
  </div>
</div>

app/views/vehicles/show.html.erb
 <div class="container">
  <h1 class="text-center"><%= @vehicle.name.capitalize %></h1>
  <hr>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-2 col-sm-4 col-xs-12">
        <%= link_to 'Back', vehicles_path, :class => "myButton", :style => "margin:0%;", :method => :get %>
      </div>
  </div>
      <hr>
  <div class="row">
    <div class="col-md-7 text-center">
      <% if @vehicle.image.present? %>
        <%= image_tag(@vehicle.image.url(:large), :class => "img-thumbnail") %>
      <% else %>
        <%= image_tag("default_car.jpg", :class => "img-thumbnail") %>
      <% end %>
      <br><br>
      <%= link_to 'Edit Vehicle', edit_vehicle_path(@vehicle.id), class: "myButton" %>
      <%= link_to 'Delete Vehicle', vehicle_path(@vehicle.id), data: { confirm: "Are you sure you want to delete this vehicle?"}, method: :delete,  class: "myButton" %><br>
    </div>

    <div class="col-md-5 text-center">
      <h2><%=@vehicle.year %> <%= @vehicle.make %> <%= @vehicle.model %></h2>
      <h3>Mileage: <%= @vehicle.mileage %></h3>
      <h4>Vin: <%= @vehicle.vin %></h4>
      <h3>License Plate: <%= @vehicle.license_plate %></h3>
      <h4>Registered in <%= @vehicle.state %></h4>
      <% if @vehicle.registration.present? %>
        Reg Expires: <%= @vehicle.registration.expiration %>
      <% else %>
        No registration entered!
      <% end %>
      <br>
      <% if @vehicle.insurance.present? %>
        Insurance Expires: <%= @vehicle.insurance.expiration_date %>
      <% else %>
        No Insurance entered!
      <% end %>
      <br><br>

      <div class="container-fluid">
        <div class="row">

          <% if @vehicle.insurance.present? %>
            <span id="insurance_modal_button_show" class="myButton" style="display:inline-block;">Insurance</span>
            <% else %>
            <%= link_to 'Add Insurance', new_vehicle_insurance_path(@vehicle.id), class: "myButton", :style => "margin-left:0%; display:inline-block;" %>
          <% end %>

          <% if @vehicle.registration.present? %>
            <span id="registration_modal_button_show" class="myButton" style="display:inline-block;">Registration</span>
          <% else %>
          <%= link_to 'Add Registration', new_vehicle_registration_path(@vehicle.id), class: "myButton", :style => "margin-right:0%; display:inline-block;" %>
          <% end %>

        </div>
      </div>

    </div>
  </div>
</div>
<hr>
<div class="text-center">
  <h2><%= @vehicle.name.capitalize %> Repairs and Maintenance Costs</h2>
  <%= link_to pie_chart(@vehicle.repairs.group(:type).sum(:repair_cost)), vehicle_repairs_path(@vehicle.id) %>
  <%= link_to 'View Repairs', vehicle_repairs_path(@vehicle.id), class: "myButton" %>
  <%= link_to 'Add Repair', new_vehicle_repair_path(@vehicle.id), class: "myButton" %><br><br>
</div>

<%= render(partial: "vehicles/insurance_modal") %>
<%= render(partial: "vehicles/registration_modal") %>