config/routes.rb
Rails.application.routes.draw do

  get '/mechanics' => 'mechanics#index'
  get '/mechanics/update' => 'mechanics#mechanics_update'

  get '/gas' => 'gas#index'
  get '/gas/coords' => 'gas#get_coords'
  get '/vehicles/selling' => 'vehicles#selling'

  match '/contact', to: 'welcomes#home', via: 'get'
  post '/contact', to: 'welcomes#contact'
  post '/transfer_vehicle', to: 'vehicles#transfer'

  devise_for :users
  root "welcomes#home"
  resources :charges
  resources :vehicles do
    resources :repairs
    resources :insurances
    resources :registrations
    resources :oilchanges, controller: 'repairs', type: 'Oilchange'
    resources :tirerotations, controller: 'repairs', type: 'Tirerotation'
    resources :inspections, controller: 'repairs', type: 'Inspection'
    resources :alignments, controller: 'repairs', type: 'Alignment'
    resources :modifications, controller: 'repairs', type: 'Modification'
    resources :otherrepairs, controller: 'repairs', type: 'Otherrepair'
  end

  resources :cars, controller: 'vehicles', type: 'Car'
  resources :trucks, controller: 'vehicles', type: 'Truck'
  resources :boats, controller: 'vehicles', type: 'Boat'
  resources :trailers, controller: 'vehicles', type: 'Trailer'
  resources :atvs, controller: 'vehicles', type: 'Atv'
  resources :motorcycles, controller: 'vehicles', type: 'Motorcycle'
  resources :waverunners, controller: 'vehicles', type: 'Waverunner'
  resources :dunebuggies, controller: 'vehicles', type: 'Dunebuggy'
  resources :other, controller: 'vehicles', type: 'Other'
end

app/models/repair.rb
class Repair < ActiveRecord::Base
  belongs_to :vehicle
  validates_presence_of :type
  has_attached_file :repair_image, :styles => {:large => "600x600", :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  #validates_attachment_content_type :repair_image, :content_type => /\Aimage\/.*\Z/
  validates_attachment_content_type :repair_image, :content_type => /^image\/(jpg|jpeg|pjpeg|png|x-png|gif)$/
  def self.types
    %w[Oilchange Tirerotation Inspection Alignment Modification Otherrepair]
  end

  #scopes
	def self.oilchanges
		where(type: 'Oilchange')
	end
  def self.tirerotations
		where(type: 'Tirerotation')
	end
  def self.inspections
    where(type: 'Inspection')
  end
  def self.alignments
    where(type: 'Alignment')
  end
  def self.modifications
    where(type: 'Modification')
  end
  def self.otherrepairs
    where(type: 'Otherrepair')
  end

  # def type_string
  #   raise "override me in the subclass"
  # end

end

app/controllers/repairs_controller.rb
class RepairsController < ApplicationController
	before_action :set_repair_type
  before_action :set_vehicle
	before_action :set_repair, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!
	before_action :authenticate_user, only: [:show, :edit, :update, :destroy]
	# before_action :set_repair_type2, except: [:index, :new]

	def index
		@repairs = @vehicle.repairs.send(repair_type).order("repair_date DESC")
	end

	def show
	end

	def edit
	end

	def update
		if @repair.update(repair_params)
			if @repair.mileage?
				@vehicle = Vehicle.find_by(id: @repair.vehicle_id)
				@vehicle.mileage = @repair.mileage
				@vehicle.save
			end
		  redirect_to vehicle_repairs_path(@vehicle.id), notice: "#{@type} was successfully updated."
		else
		  render action: 'edit'
		end
	end

	def destroy
		@repair.destroy
		redirect_to vehicle_repairs_path(@vehicle.id)
	end

	def new
		@repair = @vehicle.repairs.build
	end

	def create
		@repair = @vehicle.repairs.build(repair_params)
		if @repair.mileage?
			@vehicle = Vehicle.find_by(id: @repair.vehicle_id)
			@vehicle.mileage = @repair.mileage
			@vehicle.save
		end
    if @repair.save
      redirect_to vehicle_repairs_path(@vehicle.id), notice: "#{@type} was successfully created."
    else
      render action: 'new'
    end
	end

	private
    def set_vehicle
      @vehicle = Vehicle.find_by(id: params[:vehicle_id])
		end

		def authenticate_user
			if @vehicle.user_id != current_user.id
				redirect_to vehicles_path
			end
			unless @vehicle.repairs.find_by(id: params[:id]).present?
				redirect_to vehicles_path
			end

		end

	  def set_repair
	    @repair = repair_type_class.find_by(id: params[:id])
	  end

		def repair_type_class
      type.constantize
    end

		def set_repair_type
			@type = type()
		end

    def type()
      Repair.types.include?(params[:type]) ? params[:type] : "Repair"
    end

    def repair_type
			if type() == "Repair"
      	"all"
			else
				type.downcase.pluralize
			end
    end

    def repair_params
      params.require(type.underscore.to_sym).permit(:type, :mileage, :repair_description, :repair_date, :repair_cost, :repair_image, :repair_place, :vehicle_id)
    end
end

app/helpers/repairs_helper.rb
module RepairsHelper
  # Returns a dynamic path based on the provided parameters
  def sti_repair_path(vehicle, type = "repair", repair = nil, action = nil)
    send "#{format_action(action)}vehicle_#{format_sti(type, repair)}_path", vehicle, repair
  end

  def format_sti(type, repair)
    repair ? "#{type.underscore}" : "#{type.underscore.pluralize}"
  end

  def format_action(action)
    action ? "#{action}_" : ""
  end
end

app/views/repairs/edit.html.erb
<div class="container">
  <h1 class="text-center">Edit Repair</h1>
  <hr>
  <div style="text-align:center;">

    <%= form_for @repair, url: sti_repair_path(@vehicle, @repair.type, @repair) do |f| %>

      <h3>Type of Repair:</h3>
        <%= f.select :type, [['Oil Change', 'Oilchange'],['Alignment', 'Alignment'],['Inspection', 'Inspection'], ['Tire Rotation', 'Tirerotation'],['Modification', 'Modification'], ['Other Repair', 'Otherrepair']], {:include_blank => "Select Repair Type"}, :class => "form-control", :style => "width:150px; display:inline-block;", default: :Otherrepair %>
      <br>
      <h3>Repair Description:</h3>
        <%= f.text_area :repair_description, :placeholder => "Description of the repair", :class => "form-control" , :style => "width:250px; display:inline-block;" %>
      <br>
      <h4>Date of Repair:</h4>
        <%= f.date_select :repair_date, :class => "form-control" %>
      <br>
      <br>
      <h4>Vehicle Mileage:</h4>
        <%= f.number_field :mileage, :placeholder => "Vehicle mileage at time of repair", :class => "form-control", style: "width:250px; display:inline-block;" %>
      <br>
      <br>
      <h4>Place of Service:</h4>
        <%= f.text_field :repair_place, :placeholder => "Where was the repair done?", :class => "form-control", style: "width:60%; display:inline-block;"%>
      <br>
      <br>
      <h4>Cost ($):</h4>
        <%= f.text_field :repair_cost, :placeholder => "Repair cost", :class => "form-control", :style => "width:150px; display:inline-block" %>
      <br>
      <br>
      <%= f.file_field :repair_image, :class => "form-control", style: "width:250px; display:inline-block;" %>
      <%= f.hidden_field :vehicle_id, value: @vehicle.id %>
      <br><br><br>
      <p><%= f.submit "Update #{@repair.type_string}", :class => "myButton" %> <%= link_to 'Cancel', vehicle_repairs_path(@vehicle.id), :class => "myButton", :method => :get %></p>
      <br><br>

    <% end %>
  </div>
</div>

app/views/repairs/index.html.erb
<div class="text-center container">
  <h1>All Vehicle Repairs</h1><hr>
    <p><%= link_to 'Vehicle Details', vehicle_path(@vehicle.id), :class => "myButton pull-left", :style => "margin-top:0; margin-bottom:0;", :method => :get %></p><br>
  <hr />
  <table class="table table-hover table-striped container">
    <thead>
      <tr>
        <th class="text-center">Vehicle</th>
        <th class="text-center">Type</th>
        <th class="text-center">Description</th>
        <th class="text-center">Date</th>
        <th class="text-center">Place</th>
        <th class="text-center">Cost</th>
        <th></th>
      </tr>
    </thead>
    <% total = 0 %>
    <tbody>
      <% @repairs.each do |repair|%>
        <tr>
          <% if repair.present? %>
            <td><%= link_to(repair.vehicle.name, vehicle_path(repair.vehicle_id)) %></td>
            <td><%= link_to(repair.type_string, vehicle_repair_path(repair.vehicle_id, repair.id)) %></td>
            <td><%= repair.repair_description %></td>
            <% if repair.repair_date.present? %>
              <td><%= repair.repair_date.strftime('%b %d, %Y') %></td>
            <% else %>
              <td>No repair date entered</td>
            <% end %>
            <td><%= repair.repair_place %></td>
            <% if repair.repair_cost.present? %>
              <td>$ <%= sprintf('%.2f', repair.repair_cost) %></td>
            <% else %>
              <td><%= repair.repair_cost = 0 %></td>
            <% end %>
            <td><%= link_to 'Edit', sti_repair_path(@vehicle, repair.type, repair, :edit) %></td>
          <% end %>
          <% total += repair.repair_cost  %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <p class="pull-right" style="font-size:26px;">Total Cost of All Repairs: $ <%= sprintf('%.2f', total) %>  </p><%= link_to 'Add New Repair', new_vehicle_repair_path, :class => "myButton pull-left", :method => :get, :style => "margin-top:0; margin-bottom:0; margin-right:12%;display:inline-block" %><br>
</div>
<div class="text-center container">
  <hr>
  <h2>Repair Costs</h2>
  <h4>In Dollars</h4>
  <div><%= pie_chart @vehicle.repairs.group(:type).sum(:repair_cost) %></div>
  <hr>
</div>

app/views/repairs/new.html.erb
<div class="container">
  <h1 class="text-center">New Repair for <%= @vehicle.name.capitalize %></h1>
  <hr>
  <div style="text-align:center;">

    <%= form_for @repair, url: vehicle_repairs_path(@vehicle) do |f| %>

      <h3>Type of Repair:</h3>
        <%= f.select :type, [['Oil Change', 'Oilchange'],['Alignment', 'Alignment'],['Inspection', 'Inspection'], ['Tire Rotation', 'Tirerotation'],['Modification', 'Modification'], ['Other Repair', 'Otherrepair']], {:include_blank => "Select Repair Type"}, :class => "form-control", :style => "width:150px; display:inline-block;", default: :Otherrepair %>
      <br>
      <h3>Repair Description:</h3>
        <%= f.text_area :repair_description, :placeholder => "Description of the repair", :class => "form-control" , :style => "width:250px; display:inline-block;" %>
      <br>
      <h4>Date of Repair:</h4>
        <%= f.date_select :repair_date, :class => "form-control" %>
      <br>
      <br>
      <h4>Vehicle Mileage:</h4>
        <%= f.number_field :mileage, :placeholder => "Vehicle mileage at time of repair", :class => "form-control", style: "width:250px; display:inline-block;" %>
      <br>
      <br>
      <h4>Place of Service:</h4>
        <%= f.text_field :repair_place, :placeholder => "Where was the repair done?", :class => "form-control", style: "width:60%; display:inline-block;"%>
      <br>
      <br>
      <h4>Cost ($):</h4>
        <%= f.text_field :repair_cost, :placeholder => "Repair cost", :class => "form-control", :style => "width:150px; display:inline-block" %>
      <br>
      <br>
      <%= f.file_field :repair_image, style: "width:250px; display:inline-block;" %>
      <%= f.hidden_field :vehicle_id, value: @vehicle.id %>
      <br><br><br>
      <p><%= f.submit :class => "myButton" %> <%= link_to 'Cancel', vehicle_repairs_path(@vehicle.id), :class => "myButton", :method => :get %></p>
      <br><br>

    <% end %>
  </div>
</div>

app/views/repairs/show.html.erb
<div class="container">
  <h1 class="text-center"><%= @repair.type_string %></h1>
  <h2 class="text-center">Edit</h2>
  <hr>
  <div class="row">
    <div class="col-md-7 text-center">
      <% if @repair.repair_image.present? %>
        <%= link_to @repair.repair_image.url, rel: :lazybox do %>
          <%= image_tag(@repair.repair_image.url(:large), :class => "img-thumbnail") %>
        <% end %>
      <% else %>
        <img class="img-responsive" src="http://placehold.it/700x300" alt="">
      <% end %>
      <br/>
    </div>
    <div class="col-md-5 text-center">
      <h3><%= @repair.repair_description %></h3>
      <h3><%= @repair.repair_date.strftime('%b %d, %Y') %></h3>
      <% if @repair.repair_cost.present? %>
        <h3>Cost: $ <%= sprintf('%.2f', @repair.repair_cost) %></h3>
      <% end %>
      <h3><%= @repair.repair_place %></h3>
      <br>
      <p><%= link_to 'Edit', edit_vehicle_repair_path(@repair.vehicle_id, @repair.id), :class => "myButton" %> <%= link_to 'Back', vehicle_repairs_path(@repair.vehicle_id), :class => "myButton", :method => :get %></p>
    </div>
  </div>
</div>
<br>